name: Test

on:
  push:

# thanks to https://izumisy.work/entry/2022/03/28/140644
jobs:
  ubuntu-2204:
    name: ubuntu-2204
    runs-on: Ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2

    - uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        tags: oveus-tfhe-2204
        push: false
        load: true
        cache-from: type=gha,scope=buildx-${{ github.workflow }}-${{ github.job }}
        cache-to: type=gha,mode=max,scope=buildx-${{ github.workflow }}-${{ github.job }}

    - uses: addnab/docker-run-action@v3
      with:
        image: oveus-tfhe-2204
        run: /TFHEpp/build/test/test.sh 
  ubuntu-2404:
    name: ubuntu-2404
    runs-on: Ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
    - name: Install libraries
      run: |
        apt-get update
        apt-get upgrade -y
        apt-get install -y git build-essential g++ libomp-dev cmake git ninja-build libgoogle-perftools-dev
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build
      run: |
        cmake . -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DENABLE_TEST=ON
        cd build
        ninja
    - name: test
      run: |
        cd build
        test/test.sh